name: UltraKills
main: me.pixelmaniastudios.ultrakills.UltraKills
version: 1.0.0
api-version: 1.16
description: Customize death messages with per-world settings and Discord integration!
author: Sparklee.dev
commands:
  cdmreload:
    description: Reload the UltraKills configuration.
    usage: /cdmreload
    permission: ultrakills.admin
    permission-message: You do not have permission to execute this command.

permissions:
  ultrakill.admin:
    description: Allows admins to reload the plugin configuration.
    default: op
