name: CustomDeathMessages
main: me.pixelmaniastudios.customdeathmsg.CustomDeathMessages
version: 1.0.0
api-version: 1.16
description: Customize death messages with per-world settings and Discord integration!
author: Sparklee.dev
commands:
  cdmreload:
    description: Reload the CustomDeathMessages configuration.
    usage: /cdmreload
    permission: customdeathmessages.admin
    permission-message: You do not have permission to execute this command.

permissions:
  customdeathmessages.admin:
    description: Allows admins to reload the plugin configuration.
    default: op

